framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
        packages:
            ship_pictures:
                base_path: 'uploads/ships/pictures'
            ship_thumbnails:
                base_path: 'uploads/ships/thumbnails'
