parameters:
    env(ASSET_BASE_URL): 'http://localhost'

framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
        packages:
            ship_pictures:
                base_urls: ['%env(ASSET_BASE_URL)%/uploads/ships/pictures']
            ship_thumbnails:
                base_urls: ['%env(ASSET_BASE_URL)%/uploads/ships/thumbnails']
            manufacturer_logos:
                base_urls: ['%env(ASSET_BASE_URL)%/uploads/manufacturers/logos']
