parameters:
    env(DISCORD_ID): ''
    env(DISCORD_SECRET): ''

hwi_oauth:
    firewall_names: [main]
    resource_owners:
        discord:
            type:                oauth2
            client_id:           '%env(DISCORD_ID)%'
            client_secret:       '%env(DISCORD_SECRET)%'
            scope:               'identify'
            access_token_url:    https://discordapp.com/api/oauth2/token
            authorization_url:   https://discordapp.com/api/oauth2/authorize
            infos_url:           https://discordapp.com/api/v6/users/@me
            user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
            paths:
                identifier: id
                nickname: username
                realname: username
                discordtag: discriminator
            options:
                csrf: true
    connect:
        confirmation: false
        account_connector: App\Security\OAuthUserProvider
