nelmio_cors:
    defaults: ~
    paths:
        '^/api':
            origin_regex: true
            allow_origin: ['*']
            allow_methods: ['GET', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Link', 'X-RateLimit-Limit', 'X-RateLimit-Remaining', 'X-RateLimit-Reset']
            max_age: 3600
