oneup_flysystem:
    adapters:
        public_adapter:
            local:
                directory: '%kernel.project_dir%/public'
        ships_pictures_adapter:
            local:
                directory: '%kernel.project_dir%/public/uploads/ships/pictures'
        ships_thumbnails_adapter:
            local:
                directory: '%kernel.project_dir%/public/uploads/ships/thumbnails'
        manufacturers_logos_adapter:
            local:
                directory: '%kernel.project_dir%/public/uploads/manufacturers/logos'
    filesystems:
        public_filesystem:
            adapter: public_adapter
        ships_pictures_filesystem:
            adapter: ships_pictures_adapter
        ships_thumbnails_filesystem:
            adapter: ships_thumbnails_adapter
        manufacturers_logos_filesystem:
            adapter: manufacturers_logos_adapter
