oneup_flysystem:
    adapters:
        cache_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_S3_UPLOADS_BUCKET)%'
        ships_pictures_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_S3_UPLOADS_BUCKET)%'
                prefix: ships/pictures
        ships_thumbnails_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_S3_UPLOADS_BUCKET)%'
                prefix: ships/thumbnails
        manufacturers_logos_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_S3_UPLOADS_BUCKET)%'
                prefix: manufacturers/logos
    filesystems:
        cache_filesystem:
            adapter: cache_adapter
        ships_pictures_filesystem:
            adapter: ships_pictures_adapter
        ships_thumbnails_filesystem:
            adapter: ships_thumbnails_adapter
        manufacturers_logos_filesystem:
            adapter: manufacturers_logos_adapter
