security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        oauth_user_provider:
            id: App\Security\OAuthUserProvider
        user_entity_username:
            entity:
                class: 'App\Entity\User'
                property: 'username'
        chain_user:
            chain:
                providers: ['user_entity_username', 'oauth_user_provider']
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|build|uploads|icons|favicon\.ico|robots\.txt)/
            security: false
        main:
            anonymous: lazy
            provider: user_entity_username # default provider
            switch_user:
                provider: user_entity_username
                role: ROLE_ADMIN
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /
                user_providers: ['chain_user']
            oauth:
                provider: oauth_user_provider
                resource_owners:
                    discord: /login/check-discord
                login_path: /login/
                use_forward: false
                failure_path: /login/
                always_use_default_target_path: true
                default_target_path: /
                oauth_user_provider:
                    service: App\Security\OAuthUserProvider
                remember_me:  true
            logout:
                path: logout

    role_hierarchy:
        ROLE_MODERATOR: ROLE_USER
        ROLE_ADMIN: ROLE_MODERATOR

    access_control:
         - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
