version: '3.5'
services:
    php:
        image: sc-galaxy-php:latest
        hostname: php
        depends_on:
            - redis
    apache:
        image: sc-galaxy-apache:latest
        hostname: apache
        environment:
            PHP_HANDLER_HOST: php:9000
        depends_on:
            - php
    redis:
        image: bitnami/redis:5.0.9-debian-10-r6
        hostname: redis
