App\Entity\Ship:
    attributes:
        pagination_items_per_page: 50
        normalization_context:
            groups: ['ship:read']
    collectionOperations:
        get: ~
    itemOperations:
        get: ~
